defaults:
  - primebot_sft_openpi_pi05_mixed
  - _self_

runner:
  logger:
    experiment_name: "primebot_pi05_task03_put_items_in_washer_sft"

data:
  train_data_paths:
    - /mnt/workspace/dataset/PrimeBotHouseholdByTask/train/task_03_put_items_in_washer
  task_sampling_weights: [1.0]

actor:
  model:
    openpi:
      asset_id: primebot/task_03_put_items_in_washer
