defaults:
  - primebot_sft_openpi_pi05_mixed
  - _self_

runner:
  logger:
    experiment_name: "primebot_pi05_task01_open_washing_machine_sft"

data:
  train_data_paths:
    - /mnt/workspace/dataset/PrimeBotHouseholdByTask/train/task_01_open_washing_machine
  task_sampling_weights: [1.0]

actor:
  model:
    openpi:
      asset_id: primebot/task_01_open_washing_machine
